### ISSUE TITLE
Remote Api link missing + not working

### ISSUE THREAD

**Issue by maxchernin** [chenkie/user-authentication-api#1]
Hi, taking this course on FE masters, you specified a link
https://user-authentication-api-ocokqryugz.now.sh/api
where a remote api lives. this doesn't work. can you redeploy it and mention it in the readme file?

**Comment by chenkie** [comment]
The new link is https://user-authentication-api.now.sh/api

I'll update the readme with it :)

**Comment by maxchernin** [comment]
just saw it in the project and wanted to update. thanks.
its also worth inserting it inside the course resources
