### ISSUE TITLE
Cannot use demo api

### ISSUE THREAD

**Issue by goat-farmer** [chenkie/user-authentication-api#4]
https://user-authentication-api.now.sh/api demo api [returns the following](https://imgur.com/a/UKTrpVM)

**Comment by chenkie** [comment]
are you still getting this? I think it might have been from a cold start on now that went wrong or something. I was able to load up the API just now.

**Comment by fatchinchilla** [comment]
[I get this now](https://imgur.com/a/LxHrWlH)

**Comment by frankshei** [comment]
Yes now it works.
